export const languages = [
    { code: 'en', label: 'English' },
    { code: 'ru', label: 'Русский' },
    { code: 'ar', label: 'العربية' },
    { code: 'es', label: 'Español' },
    { code: 'tr', label: 'Türkçe' },
    { code: 'pt', label: 'Português' },
    { code: 'id', label: 'Bahasa Indonesia' },
    { code: 'hi', label: 'हिन्दी' },
    { code: 'fr', label: 'Français' },
    { code: 'it', label: 'Italiano' },
    { code: 'de', label: 'Deutsch' },
    { code: 'ja', label: '日本語' },
    { code: 'nl', label: 'Nederlands' },
    { code: 'pl', label: 'Polski' },
    { code: 'sv', label: 'Svenska' },
    { code: 'da', label: 'Dansk' },
    { code: 'fi', label: 'Suomi' },
    { code: 'no', label: 'Norsk' },
    { code: 'ko', label: '한국어' },
    { code: 'el', label: 'Ελληνικά' },
    { code: 'cs', label: 'Čeština' },
    { code: 'hu', label: 'Magyar' },
    { code: 'th', label: 'ไทย' },
  ];
  
  export const speechLanguages = [
    { code: 'en-US', label: 'English US' },
    { code: 'en-GB', label: 'English UK' },
    { code: 'ru-RU', label: 'Русский RU' },
    { code: 'es-ES', label: 'Español ES' },
    { code: 'es-MX', label: 'Español MX' },
    { code: 'tr-TR', label: 'Türkçe TR' },
    { code: 'fr-FR', label: 'Français FR' },
    { code: 'fr-CA', label: 'Français CA' },
    { code: 'de-DE', label: 'Deutsch DE' },
    { code: 'it-IT', label: 'Italiano IT' },
    { code: 'ja-JP', label: '日本語 JP' },
    { code: 'ko-KR', label: '한국어 KR' },
    { code: 'zh-CN', label: '中文简体 CN' },
    { code: 'zh-TW', label: '中文繁體 TW' },
    { code: 'ar-SA', label: 'العربية SA' },
    { code: 'hi-IN', label: 'हिन्दी IN' },
    { code: 'id-ID', label: 'Bahasa Indonesia ID' },
    { code: 'pt-BR', label: 'Português BR' },
    { code: 'pt-PT', label: 'Português PT' },
    { code: 'nl-NL', label: 'Nederlands NL' },
    { code: 'pl-PL', label: 'Polski PL' },
    { code: 'sv-SE', label: 'Svenska SE' },
    { code: 'da-DK', label: 'Dansk DK' },
    { code: 'fi-FI', label: 'Suomi FI' },
    { code: 'no-NO', label: 'Norsk NO' },
    { code: 'th-TH', label: 'ไทย TH' },
    { code: 'cs-CZ', label: 'Čeština CZ' },
    { code: 'hu-HU', label: 'Magyar HU' },
    { code: 'el-GR', label: 'Ελληνικά GR' },
    { code: 'ro-RO', label: 'Română RO' },
    { code: 'uk-UA', label: 'Українська UA' },
    { code: 'vi-VN', label: 'Tiếng Việt VN' }
  ];
  